### ISSUE TITLE
destinationBranch & sourceBranch

### ISSUE THREAD

**Issue by okram999** [dlively1/sf-packager#11]
First, i have to admit its a nice handy project. 

Can you elaborate more on what each of these branches are intended to be for? I dont see expected content of the package.xml and the components while using this node package. 

My use case:
master branch: i have this branch as the metadata deployed to prod. Useing this as reference. 
dev branch: where new changes are pushed into. 

So, when i do `sfpackage dev master ./deploy/`, i dont see all the changes a part of it under the `deploy` folder created. 

Also just curious, are you using this in your prod deployment? Does it support all the metadata's supported by the force metadata API? 

Finally, looking at the components - it looks as though its deploying the full content and not what was only changed. Please confirm

**Comment by manuerwin** [comment]
This tool takes the file names that are output from running the git diff command against two commits (where a git "branch" is merely a pointer to a commit) and copies the entire file into your chosen directory.
Try switching around the branch references you are providing e.g.
sfpackage master dev ./deploy/ as you've said that master is your reference.
Assuming you are making changes in your dev branch and wanting to migrate those changes to master?

**Comment by okram999** [comment]
Is this a prod ready solution or just a prototype

**Comment by pyao-bwc** [comment]
I've been using it in prod, works great with the exception of two things that I've found:
* It includes just the lightning component bundle resources that have changed in the deployment package. When deploying, Salesforce ends up deleting the unchanged resources (the ones not included). I end up having to copy those bundles over manually (and wish I knew how to fix it).
* It doesn't include the required but empty package.xml for destructive changes. I end up having to create that manually.

It's a great tool - I wonder how others are building their release packages if not using this! Thanks Dan!

**Comment by okram999** [comment]
thanks @manuerwin @pyao-bwc - for the responses. I have some follow up questions. 
1. how much time does this tool take to generate the unmannaged package for you. For me, at the end of a release cycle, i have a git diff line count of around 1315465. 

2. Does this tool, generates the package.xml & components only for the changes of include everything. E.g. Say Opportunity.object, if i added only a field - does it generate the package with the new field only. Or puts the entire opportunity.object. The same for profiles, permSets etc.

**Comment by pyao-bwc** [comment]
1. We basically only have Apex and Lightning in our repository, so our diff is on the order of ~2k lines. It doesn't take much time at all to run.

2. Can't comment as we don't track those metadata. I'd guess it was the whole file, though.

**Comment by jagrelot** [comment]
I have no idea how to use this tool. I'm using the commands given in the readme, but no directories or files are created. I'm getting "File name "src/destructiveChanges.txt" cannot be processed, exiting". I'm not sure where the issue is. Are there better instructions available?

**Comment by dlively1** [comment]
@jagrelot what happens when you run the following command?

```
git --no-pager diff feature-branch dev-master --name-status
```

Where `feature-branch` and `dev-master` are the two branches you are comparing?

**Comment by jagrelot** [comment]
I get the list of the metadata that was added, deleted or modified. When I run the sfpackage dev master ./deploy/ command this is the last line in the console "File name "src/destructiveChanges.txt" cannot be processed, exiting"

**Comment by dlively1** [comment]
Is `src/destructiveChanges.txt` part of your repository?

If so we might need to exclude that, similar to how the `src/package.xml` is ignored 

https://github.com/dlively1/sf-packager/blob/58cc1f9b408e2d82ae4a36498f761c5333bed7f8/index.js#L78-L81

**Comment by jagrelot** [comment]
I added an if statement and now I am acutally able to produce something. Thanks!
`if(fileName === 'src/destructiveChanges.xml') { 
     return; 
 } `

**Comment by dlively1** [comment]
@jagrelot awesome, great to hear.

Feel free to open a pull request and I would be happy to bring in the changes.
