### ISSUE TITLE
Handle support for customMetadata components

### ISSUE THREAD

**Issue by dlively1** [dlively1/sf-packager#13]
The generated package info incorrectly names customMetadata components. The `package.xml` file needs to prepend the metadata type to the name

**Comment by nav0229** [comment]
Hi

This is an awesome utility and I am trying to use it  for Salesforce deployments. When are you planing to fix above said issue where package.xml has some incorrect formatting? (Ex: <name\> )

**Comment by dlively1** [comment]
Hey @nav0229,

I hope to dig into it a bit at some point in the near future. I'll keep you posted. Also happy to take contributions if you would like to open a pull request.
