### ISSUE TITLE
Why it is not published in npm?

### ISSUE THREAD

**Issue by froucher** [dlively1/sf-packager#17]
Hi,

Recently I published this package in npm: https://www.npmjs.com/package/sf-git-packager

Maybe will be great to publish it as sf-packager.

Please let me know if you need help.

Thanks.

**Comment by dlively1** [comment]
Great question, I had planned on doing so but wanted to get some test coverage before doing so. 

At this point, there are quite a few people using it and it might just make everything easier if I went ahead and did so now.

I have a few other updates I will be bringing in within the next few days, including making some updates on our internal build system that uses this tool. Seems like the right time to do this, I will let you know once it has been published.

**Comment by dlively1** [comment]
Hey, @froucher I published this to npm now. I have been making some updates to the project it would be great to deprecate your npm package in favor of the official one tied to this codebase.

https://www.npmjs.com/package/sf-packager
