### ISSUE TITLE
Support for SFDX project structures

### ISSUE THREAD

**Issue by 0cv** [dlively1/sf-packager#72]
Unless I'm doing something wrong, I don't think this tool supports sfdx based projects. It ends up generating an empty package.xml although there is more between the two branches (`git --no-pager diff ...`)
![image](https://user-images.githubusercontent.com/1253866/101519985-212d1100-3984-11eb-9414-4f6098f41a1b.png)

**Comment by dlively1** [comment]
@0cv you are correct the tool does not currently support the SFDX project structure. I'd love to see this functionality added in the future.

I continue to maintain this tool but no longer do as much SFDC development. I still leverage this tool to support my companies SFDC development process which is still using the legacy format.

I'd be open to accepting any contributions and would be happy to tackle this feature if enough people are interested.

**Comment by 0cv** [comment]
Thanks for the answer. Don't want to advertise other apps, but in case it helps someone else, I've been hunting the internet for something doing this on sfdx project and landed on that project which did so far exactly what I expecting from ithttps://github.com/scolladon/sfdx-git-delta
